// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, type, name, last_activity_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, type, name, avatar_url, last_activity_at, created_at
`

type CreateConversationParams struct {
	ID   pgtype.UUID `json:"id"`
	Type string      `json:"type"`
	Name pgtype.Text `json:"name"`
}

type CreateConversationRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	Name           pgtype.Text        `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Tạo conversation mới (DM hoặc GROUP)
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ID, arg.Type, arg.Name)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO conversation_participants (id, conversation_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, conversation_id, user_id, role, last_read_at, joined_at
`

type CreateParticipantParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
}

type CreateParticipantRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

// Thêm participant vào conversation
func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (CreateParticipantRow, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
	)
	var i CreateParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.LastReadAt,
		&i.JoinedAt,
	)
	return i, err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT c.id
FROM conversations c
JOIN conversation_participants cp1 ON cp1.conversation_id = c.id
JOIN conversation_participants cp2 ON cp2.conversation_id = c.id
WHERE c.type = 'DM'
    AND cp1.user_id = $1
    AND cp2.user_id = $2
    AND cp1.left_at IS NULL
    AND cp2.left_at IS NULL
LIMIT 1
`

type FindDMConversationParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

// Tìm DM conversation giữa 2 users (dùng cho reuse khi re-friend)
func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.UserID, arg.UserID_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT c.id, c.type, c.name, c.avatar_url, c.last_activity_at, c.created_at
FROM conversations c
WHERE c.id = $1
`

type GetConversationByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Type           string             `json:"type"`
	Name           pgtype.Text        `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Lấy chi tiết conversation theo ID
func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (GetConversationByIDRow, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i GetConversationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationDetails = `-- name: GetConversationDetails :one
SELECT
    c.id,
    c.type,
    c.name,
    c.avatar_url,
    c.last_activity_at,
    COUNT(m_unread.id) AS unread_count,
    -- Thông tin other_user cho DM
    CASE 
        WHEN c.type = 'DM' THEN (
            SELECT cp2.user_id 
            FROM conversation_participants cp2 
            WHERE cp2.conversation_id = c.id 
            AND cp2.user_id != $1 
            AND cp2.left_at IS NULL
            LIMIT 1
        )
    END AS other_user_id,
    -- Friendship status cho DM
    CASE
        WHEN c.type = 'DM' THEN (
            SELECT f.status
            FROM friendships f
            WHERE (f.requester_id = $1 AND f.addressee_id = (
                SELECT cp2.user_id FROM conversation_participants cp2 WHERE cp2.conversation_id = c.id AND cp2.user_id != $1 LIMIT 1
            )) OR (f.addressee_id = $1 AND f.requester_id = (
                SELECT cp2.user_id FROM conversation_participants cp2 WHERE cp2.conversation_id = c.id AND cp2.user_id != $1 LIMIT 1
            ))
            LIMIT 1
        )
    END AS friendship_status
FROM conversations c
LEFT JOIN conversation_participants cp ON cp.conversation_id = c.id AND cp.user_id = $1
LEFT JOIN messages m_unread ON 
    m_unread.conversation_id = c.id
    AND m_unread.deleted_at IS NULL
    AND m_unread.sender_id != $1
    AND m_unread.created_at > COALESCE(cp.last_read_at, '1970-01-01')
WHERE c.id = $2
GROUP BY c.id
`

type GetConversationDetailsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetConversationDetailsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Type             string             `json:"type"`
	Name             pgtype.Text        `json:"name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	UnreadCount      int64              `json:"unread_count"`
	OtherUserID      interface{}        `json:"other_user_id"`
	FriendshipStatus interface{}        `json:"friendship_status"`
}

// Lấy chi tiết conversation với unread count và friendship status
func (q *Queries) GetConversationDetails(ctx context.Context, arg GetConversationDetailsParams) (GetConversationDetailsRow, error) {
	row := q.db.QueryRow(ctx, getConversationDetails, arg.UserID, arg.ID)
	var i GetConversationDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.AvatarUrl,
		&i.LastActivityAt,
		&i.UnreadCount,
		&i.OtherUserID,
		&i.FriendshipStatus,
	)
	return i, err
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT 
    cp.id,
    cp.user_id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.status,
    cp.role,
    cp.joined_at
FROM conversation_participants cp
JOIN users u ON u.id = cp.user_id
WHERE cp.conversation_id = $1
    AND cp.left_at IS NULL
ORDER BY cp.joined_at
`

type GetConversationParticipantsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Status      string             `json:"status"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

// Lấy danh sách participants của conversation
func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID pgtype.UUID) ([]GetConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationParticipantsRow
	for rows.Next() {
		var i GetConversationParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendshipStatus = `-- name: GetFriendshipStatus :one
SELECT status FROM friendships
WHERE ((requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1))
    AND status = 'ACCEPTED'
LIMIT 1
`

type GetFriendshipStatusParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

// Kiểm tra status friendship giữa 2 users
func (q *Queries) GetFriendshipStatus(ctx context.Context, arg GetFriendshipStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getFriendshipStatus, arg.RequesterID, arg.AddresseeID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participants
    WHERE conversation_id = $1 
    AND user_id = $2 
    AND left_at IS NULL
) AS is_member
`

type IsConversationMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Kiểm tra user có phải member của conversation không
func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isGroupAdmin = `-- name: IsGroupAdmin :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participants
    WHERE conversation_id = $1 
    AND user_id = $2 
    AND role = 'ADMIN'
    AND left_at IS NULL
) AS is_admin
`

type IsGroupAdminParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Kiểm tra user có phải admin của group không
func (q *Queries) IsGroupAdmin(ctx context.Context, arg IsGroupAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupAdmin, arg.ConversationID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT
    c.id,
    c.type,
    c.name,
    c.avatar_url,
    c.last_activity_at,
    m_last.id AS last_message_id,
    m_last.body AS last_message_body,
    m_last.type AS last_message_type,
    m_last.created_at AS last_message_created_at,
    m_last.sender_id AS last_message_sender_id,
    u_last.display_name AS last_message_sender_name,
    u_last.avatar_url AS last_message_sender_avatar,
    COUNT(m_unread.id) AS unread_count,
    -- Thông tin other_user cho DM
    CASE 
        WHEN c.type = 'DM' THEN (
            SELECT cp2.user_id 
            FROM conversation_participants cp2 
            WHERE cp2.conversation_id = c.id 
            AND cp2.user_id != $1 
            AND cp2.left_at IS NULL
            LIMIT 1
        )
    END AS other_user_id,
    -- Friendship status cho DM
    CASE
        WHEN c.type = 'DM' THEN (
            SELECT f.status
            FROM friendships f
            WHERE (f.requester_id = $1 AND f.addressee_id = (
                SELECT cp2.user_id FROM conversation_participants cp2 WHERE cp2.conversation_id = c.id AND cp2.user_id != $1 LIMIT 1
            )) OR (f.addressee_id = $1 AND f.requester_id = (
                SELECT cp2.user_id FROM conversation_participants cp2 WHERE cp2.conversation_id = c.id AND cp2.user_id != $1 LIMIT 1
            ))
            LIMIT 1
        )
    END AS friendship_status
FROM conversation_participants cp
JOIN conversations c ON c.id = cp.conversation_id
LEFT JOIN messages m_last ON m_last.id = c.last_message_id
LEFT JOIN users u_last ON u_last.id = m_last.sender_id
LEFT JOIN messages m_unread ON 
    m_unread.conversation_id = c.id
    AND m_unread.deleted_at IS NULL
    AND m_unread.sender_id != $1
    AND m_unread.created_at > COALESCE(cp.last_read_at, '1970-01-01')
WHERE cp.user_id = $1
    AND cp.left_at IS NULL
    AND ($2::timestamptz IS NULL OR c.last_activity_at < $2)
    AND ($3::uuid IS NULL OR c.id < $3)
GROUP BY c.id, m_last.id, m_last.body, m_last.type, m_last.created_at, 
         m_last.sender_id, u_last.display_name, u_last.avatar_url
ORDER BY c.last_activity_at DESC, c.id DESC
LIMIT $4
`

type ListConversationsByUserParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.UUID        `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type ListConversationsByUserRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Type                    string             `json:"type"`
	Name                    pgtype.Text        `json:"name"`
	AvatarUrl               pgtype.Text        `json:"avatar_url"`
	LastActivityAt          pgtype.Timestamptz `json:"last_activity_at"`
	LastMessageID           pgtype.UUID        `json:"last_message_id"`
	LastMessageBody         pgtype.Text        `json:"last_message_body"`
	LastMessageType         pgtype.Text        `json:"last_message_type"`
	LastMessageCreatedAt    pgtype.Timestamptz `json:"last_message_created_at"`
	LastMessageSenderID     pgtype.UUID        `json:"last_message_sender_id"`
	LastMessageSenderName   pgtype.Text        `json:"last_message_sender_name"`
	LastMessageSenderAvatar pgtype.Text        `json:"last_message_sender_avatar"`
	UnreadCount             int64              `json:"unread_count"`
	OtherUserID             interface{}        `json:"other_user_id"`
	FriendshipStatus        interface{}        `json:"friendship_status"`
}

// Lấy danh sách conversations của user với unread count và last message
// Sử dụng cursor pagination dựa trên last_activity_at
func (q *Queries) ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]ListConversationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByUserRow
	for rows.Next() {
		var i ListConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.AvatarUrl,
			&i.LastActivityAt,
			&i.LastMessageID,
			&i.LastMessageBody,
			&i.LastMessageType,
			&i.LastMessageCreatedAt,
			&i.LastMessageSenderID,
			&i.LastMessageSenderName,
			&i.LastMessageSenderAvatar,
			&i.UnreadCount,
			&i.OtherUserID,
			&i.FriendshipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET name = COALESCE($2, name),
    avatar_url = COALESCE($3, avatar_url),
    avatar_cloudinary_id = COALESCE($4, avatar_cloudinary_id),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, avatar_url, updated_at
`

type UpdateConversationParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               pgtype.Text `json:"name"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	AvatarCloudinaryID pgtype.Text `json:"avatar_cloudinary_id"`
}

type UpdateConversationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      pgtype.Text        `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Cập nhật tên hoặc avatar của conversation
func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (UpdateConversationRow, error) {
	row := q.db.QueryRow(ctx, updateConversation,
		arg.ID,
		arg.Name,
		arg.AvatarUrl,
		arg.AvatarCloudinaryID,
	)
	var i UpdateConversationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastActivity = `-- name: UpdateLastActivity :exec
UPDATE conversations
SET last_activity_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// Cập nhật last_activity_at khi có hoạt động mới
func (q *Queries) UpdateLastActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastActivity, id)
	return err
}

const updateLastMessage = `-- name: UpdateLastMessage :exec
UPDATE conversations
SET last_message_id = $2,
    last_activity_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateLastMessageParams struct {
	ID            pgtype.UUID `json:"id"`
	LastMessageID pgtype.UUID `json:"last_message_id"`
}

// Cập nhật last_message_id sau khi gửi tin nhắn
func (q *Queries) UpdateLastMessage(ctx context.Context, arg UpdateLastMessageParams) error {
	_, err := q.db.Exec(ctx, updateLastMessage, arg.ID, arg.LastMessageID)
	return err
}

const updateLastRead = `-- name: UpdateLastRead :one
UPDATE conversation_participants
SET last_read_message_id = $3,
    last_read_at = NOW()
WHERE conversation_id = $1 
    AND user_id = $2
RETURNING id, last_read_message_id, last_read_at
`

type UpdateLastReadParams struct {
	ConversationID    pgtype.UUID `json:"conversation_id"`
	UserID            pgtype.UUID `json:"user_id"`
	LastReadMessageID pgtype.UUID `json:"last_read_message_id"`
}

type UpdateLastReadRow struct {
	ID                pgtype.UUID        `json:"id"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
}

// Cập nhật last_read_message_id và last_read_at
func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) (UpdateLastReadRow, error) {
	row := q.db.QueryRow(ctx, updateLastRead, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	var i UpdateLastReadRow
	err := row.Scan(&i.ID, &i.LastReadMessageID, &i.LastReadAt)
	return i, err
}
