// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (id, requester_id, addressee_id, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'PENDING', NOW(), NOW())
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type CreateFriendshipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const findDMConversationBetweenUsers = `-- name: FindDMConversationBetweenUsers :one
SELECT c.id
FROM conversations c
JOIN conversation_participants cp1 ON cp1.conversation_id = c.id AND cp1.user_id = $1 AND cp1.left_at IS NULL
JOIN conversation_participants cp2 ON cp2.conversation_id = c.id AND cp2.user_id = $2 AND cp2.left_at IS NULL
WHERE c.type = 'DM'
LIMIT 1
`

type FindDMConversationBetweenUsersParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) FindDMConversationBetweenUsers(ctx context.Context, arg FindDMConversationBetweenUsersParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findDMConversationBetweenUsers, arg.UserID, arg.UserID_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getFriendshipBetweenUsers = `-- name: GetFriendshipBetweenUsers :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at
FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
LIMIT 1
`

type GetFriendshipBetweenUsersParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendshipBetweenUsers(ctx context.Context, arg GetFriendshipBetweenUsersParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipBetweenUsers, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at
FROM friendships
WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFriendsByUser = `-- name: ListFriendsByUser :many
SELECT
    f.id AS friendship_id,
    CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END AS friend_id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.status,
    u.last_seen_at,
    f.created_at AS became_friends_at
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END
WHERE (f.requester_id = $1 OR f.addressee_id = $1)
  AND f.status = 'ACCEPTED'
ORDER BY f.updated_at DESC
`

type ListFriendsByUserRow struct {
	FriendshipID    pgtype.UUID        `json:"friendship_id"`
	FriendID        interface{}        `json:"friend_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Status          string             `json:"status"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	BecameFriendsAt pgtype.Timestamptz `json:"became_friends_at"`
}

func (q *Queries) ListFriendsByUser(ctx context.Context, requesterID pgtype.UUID) ([]ListFriendsByUserRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByUser, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByUserRow
	for rows.Next() {
		var i ListFriendsByUserRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.FriendID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
			&i.LastSeenAt,
			&i.BecameFriendsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsReceived = `-- name: ListPendingRequestsReceived :many
SELECT
    f.id AS request_id,
    f.requester_id AS from_user_id,
    u.username,
    u.display_name,
    u.avatar_url,
    f.created_at AS requested_at
FROM friendships f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1
  AND f.status = 'PENDING'
ORDER BY f.created_at DESC
`

type ListPendingRequestsReceivedRow struct {
	RequestID   pgtype.UUID        `json:"request_id"`
	FromUserID  pgtype.UUID        `json:"from_user_id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
}

func (q *Queries) ListPendingRequestsReceived(ctx context.Context, addresseeID pgtype.UUID) ([]ListPendingRequestsReceivedRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsReceived, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsReceivedRow
	for rows.Next() {
		var i ListPendingRequestsReceivedRow
		if err := rows.Scan(
			&i.RequestID,
			&i.FromUserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsSent = `-- name: ListPendingRequestsSent :many
SELECT
    f.id AS request_id,
    f.addressee_id AS to_user_id,
    u.username,
    u.display_name,
    u.avatar_url,
    f.created_at AS requested_at
FROM friendships f
JOIN users u ON u.id = f.addressee_id
WHERE f.requester_id = $1
  AND f.status = 'PENDING'
ORDER BY f.created_at DESC
`

type ListPendingRequestsSentRow struct {
	RequestID   pgtype.UUID        `json:"request_id"`
	ToUserID    pgtype.UUID        `json:"to_user_id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
}

func (q *Queries) ListPendingRequestsSent(ctx context.Context, requesterID pgtype.UUID) ([]ListPendingRequestsSentRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsSent, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsSentRow
	for rows.Next() {
		var i ListPendingRequestsSentRow
		if err := rows.Scan(
			&i.RequestID,
			&i.ToUserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersWithRelationship = `-- name: SearchUsersWithRelationship :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.status,
    CASE
        WHEN f_accepted.id IS NOT NULL THEN 'ACCEPTED'
        WHEN f_pending_sent.id IS NOT NULL THEN 'PENDING_SENT'
        WHEN f_pending_received.id IS NOT NULL THEN 'PENDING_RECEIVED'
        ELSE 'NONE'
    END AS relationship
FROM users u
LEFT JOIN friendships f_accepted ON (
    (f_accepted.requester_id = $1 AND f_accepted.addressee_id = u.id) OR
    (f_accepted.addressee_id = $1 AND f_accepted.requester_id = u.id)
) AND f_accepted.status = 'ACCEPTED'
LEFT JOIN friendships f_pending_sent ON (
    f_pending_sent.requester_id = $1 AND f_pending_sent.addressee_id = u.id
) AND f_pending_sent.status = 'PENDING'
LEFT JOIN friendships f_pending_received ON (
    f_pending_received.addressee_id = $1 AND f_pending_received.requester_id = u.id
) AND f_pending_received.status = 'PENDING'
WHERE u.id <> $1
  AND (u.username ILIKE '%' || $2 || '%' OR u.display_name ILIKE '%' || $2 || '%')
ORDER BY u.display_name
LIMIT $3
`

type SearchUsersWithRelationshipParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	Column2     pgtype.Text `json:"column_2"`
	Limit       int32       `json:"limit"`
}

type SearchUsersWithRelationshipRow struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Status       string      `json:"status"`
	Relationship string      `json:"relationship"`
}

func (q *Queries) SearchUsersWithRelationship(ctx context.Context, arg SearchUsersWithRelationshipParams) ([]SearchUsersWithRelationshipRow, error) {
	rows, err := q.db.Query(ctx, searchUsersWithRelationship, arg.RequesterID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersWithRelationshipRow
	for rows.Next() {
		var i SearchUsersWithRelationshipRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, updateFriendshipStatus, arg.ID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
