// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO attachments (
    id, message_id, storage_type, file_type, url, thumbnail_url,
    original_name, mime_type, size_bytes, width, height, duration_secs
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, message_id, storage_type, file_type, url, thumbnail_url,
    original_name, mime_type, size_bytes, width, height, duration_secs, created_at
`

type CreateAttachmentParams struct {
	ID           pgtype.UUID `json:"id"`
	MessageID    pgtype.UUID `json:"message_id"`
	StorageType  string      `json:"storage_type"`
	FileType     string      `json:"file_type"`
	Url          string      `json:"url"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	OriginalName string      `json:"original_name"`
	MimeType     string      `json:"mime_type"`
	SizeBytes    int64       `json:"size_bytes"`
	Width        pgtype.Int4 `json:"width"`
	Height       pgtype.Int4 `json:"height"`
	DurationSecs pgtype.Int4 `json:"duration_secs"`
}

// SENT < DELIVERED < READ
// Tạo attachment record liên kết với message
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.MessageID,
		arg.StorageType,
		arg.FileType,
		arg.Url,
		arg.ThumbnailUrl,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.DurationSecs,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.StorageType,
		&i.FileType,
		&i.Url,
		&i.ThumbnailUrl,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, sender_id, body, type, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, conversation_id, sender_id, body, type, status, created_at, deleted_at
`

type CreateMessageParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Body           pgtype.Text `json:"body"`
	Type           string      `json:"type"`
	Status         string      `json:"status"`
}

type CreateMessageRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Body           pgtype.Text        `json:"body"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// Tạo message mới (TEXT hoặc ATTACHMENT)
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Body,
		arg.Type,
		arg.Status,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestMessageID = `-- name: GetLatestMessageID :one
SELECT id FROM messages
WHERE conversation_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Lấy ID của tin nhắn mới nhất trong conversation
func (q *Queries) GetLatestMessageID(ctx context.Context, conversationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestMessageID, conversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT 
    m.id,
    m.conversation_id,
    m.sender_id,
    u.display_name AS sender_display_name,
    u.username AS sender_username,
    u.avatar_url AS sender_avatar_url,
    m.body,
    m.type,
    m.status,
    m.created_at,
    m.deleted_at,
    a.id AS attachment_id,
    a.storage_type,
    a.file_type,
    a.url,
    a.thumbnail_url,
    a.original_name,
    a.mime_type,
    a.size_bytes,
    a.width,
    a.height,
    a.duration_secs
FROM messages m
JOIN users u ON u.id = m.sender_id
LEFT JOIN attachments a ON a.message_id = m.id
WHERE m.id = $1 AND m.deleted_at IS NULL
`

type GetMessageByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	SenderID          pgtype.UUID        `json:"sender_id"`
	SenderDisplayName string             `json:"sender_display_name"`
	SenderUsername    string             `json:"sender_username"`
	SenderAvatarUrl   pgtype.Text        `json:"sender_avatar_url"`
	Body              pgtype.Text        `json:"body"`
	Type              string             `json:"type"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AttachmentID      pgtype.UUID        `json:"attachment_id"`
	StorageType       pgtype.Text        `json:"storage_type"`
	FileType          pgtype.Text        `json:"file_type"`
	Url               pgtype.Text        `json:"url"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnail_url"`
	OriginalName      pgtype.Text        `json:"original_name"`
	MimeType          pgtype.Text        `json:"mime_type"`
	SizeBytes         pgtype.Int8        `json:"size_bytes"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationSecs      pgtype.Int4        `json:"duration_secs"`
}

// Lấy message theo ID (không bao gồm deleted)
func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.SenderDisplayName,
		&i.SenderUsername,
		&i.SenderAvatarUrl,
		&i.Body,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.AttachmentID,
		&i.StorageType,
		&i.FileType,
		&i.Url,
		&i.ThumbnailUrl,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)
FROM messages m
WHERE m.conversation_id = $1
    AND m.deleted_at IS NULL
    AND m.sender_id != $2
    AND m.created_at > COALESCE(
        (SELECT last_read_at FROM conversation_participants 
         WHERE conversation_id = $1 AND user_id = $2),
        '1970-01-01'
    )
`

type GetUnreadCountParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	SenderID       pgtype.UUID `json:"sender_id"`
}

// Đếm số tin nhắn chưa đọc trong conversation cho user cụ thể
func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.ConversationID, arg.SenderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessages = `-- name: ListMessages :many
SELECT 
    m.id,
    m.conversation_id,
    m.sender_id,
    u.display_name AS sender_display_name,
    u.username AS sender_username,
    u.avatar_url AS sender_avatar_url,
    m.body,
    m.type,
    m.status,
    m.created_at,
    m.deleted_at,
    -- Attachment info (nếu có)
    a.id AS attachment_id,
    a.storage_type,
    a.file_type,
    a.url,
    a.thumbnail_url,
    a.original_name,
    a.mime_type,
    a.size_bytes,
    a.width,
    a.height,
    a.duration_secs
FROM messages m
JOIN users u ON u.id = m.sender_id
LEFT JOIN attachments a ON a.message_id = m.id
WHERE m.conversation_id = $1
    AND m.deleted_at IS NULL
    AND (
        $2::timestamptz IS NULL OR $3::uuid IS NULL
        OR (m.created_at, m.id) < ($2, $3)
    )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Column2        pgtype.Timestamptz `json:"column_2"`
	Column3        pgtype.UUID        `json:"column_3"`
	Limit          int32              `json:"limit"`
}

type ListMessagesRow struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	SenderID          pgtype.UUID        `json:"sender_id"`
	SenderDisplayName string             `json:"sender_display_name"`
	SenderUsername    string             `json:"sender_username"`
	SenderAvatarUrl   pgtype.Text        `json:"sender_avatar_url"`
	Body              pgtype.Text        `json:"body"`
	Type              string             `json:"type"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AttachmentID      pgtype.UUID        `json:"attachment_id"`
	StorageType       pgtype.Text        `json:"storage_type"`
	FileType          pgtype.Text        `json:"file_type"`
	Url               pgtype.Text        `json:"url"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnail_url"`
	OriginalName      pgtype.Text        `json:"original_name"`
	MimeType          pgtype.Text        `json:"mime_type"`
	SizeBytes         pgtype.Int8        `json:"size_bytes"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationSecs      pgtype.Int4        `json:"duration_secs"`
}

// Lấy danh sách messages với cursor pagination
// Sử dụng composite cursor (created_at, id) để đảm bảo deterministic ordering
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConversationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderDisplayName,
			&i.SenderUsername,
			&i.SenderAvatarUrl,
			&i.Body,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.AttachmentID,
			&i.StorageType,
			&i.FileType,
			&i.Url,
			&i.ThumbnailUrl,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.DurationSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :execrows
UPDATE messages
SET deleted_at = NOW(),
    body = NULL,
    updated_at = NOW()
WHERE id = $1 
    AND sender_id = $2
    AND deleted_at IS NULL
`

type SoftDeleteMessageParams struct {
	ID       pgtype.UUID `json:"id"`
	SenderID pgtype.UUID `json:"sender_id"`
}

// Soft delete message: chỉ sender mới được xóa tin nhắn của mình
// Set deleted_at=NOW(), body=NULL (theo docs/7 phần 7)
func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMessage, arg.ID, arg.SenderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages
SET status = $2,
    updated_at = NOW()
WHERE conversation_id = $1
    AND sender_id != $3
    AND status < $2
`

type UpdateMessageStatusParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Status         string      `json:"status"`
	SenderID       pgtype.UUID `json:"sender_id"`
}

// Cập nhật status của message (SENT -> DELIVERED -> READ)
// Chỉ dùng cho DM
func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus, arg.ConversationID, arg.Status, arg.SenderID)
	return err
}
