// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID           pgtype.UUID        `json:"id"`
	MessageID    pgtype.UUID        `json:"message_id"`
	StorageType  string             `json:"storage_type"`
	FileType     string             `json:"file_type"`
	Url          string             `json:"url"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	OriginalName string             `json:"original_name"`
	MimeType     string             `json:"mime_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Width        pgtype.Int4        `json:"width"`
	Height       pgtype.Int4        `json:"height"`
	DurationSecs pgtype.Int4        `json:"duration_secs"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID                 pgtype.UUID        `json:"id"`
	Type               string             `json:"type"`
	Name               pgtype.Text        `json:"name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	AvatarCloudinaryID pgtype.Text        `json:"avatar_cloudinary_id"`
	LastMessageID      pgtype.UUID        `json:"last_message_id"`
	LastActivityAt     pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ConversationParticipant struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Role              string             `json:"role"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	LeftAt            pgtype.Timestamptz `json:"left_at"`
}

type Friendship struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	AddresseeID pgtype.UUID        `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Body           pgtype.Text        `json:"body"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID            pgtype.UUID        `json:"id"`
	RecipientID   pgtype.UUID        `json:"recipient_id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	Type          string             `json:"type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	ReferenceType string             `json:"reference_type"`
	IsRead        bool               `json:"is_read"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ReadAt        pgtype.Timestamptz `json:"read_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IsRevoked  bool               `json:"is_revoked"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	Username           string             `json:"username"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        string             `json:"display_name"`
	Bio                pgtype.Text        `json:"bio"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	AvatarCloudinaryID pgtype.Text        `json:"avatar_cloudinary_id"`
	Status             string             `json:"status"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
