// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, recipient_id, actor_id, type, reference_id, reference_type, is_read, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, FALSE, NOW())
RETURNING id, recipient_id, actor_id, type, reference_id, reference_type, is_read, created_at, read_at
`

type CreateNotificationParams struct {
	RecipientID   pgtype.UUID `json:"recipient_id"`
	ActorID       pgtype.UUID `json:"actor_id"`
	Type          string      `json:"type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	ReferenceType string      `json:"reference_type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.ReferenceID,
		arg.ReferenceType,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const deleteNotificationByReference = `-- name: DeleteNotificationByReference :exec
DELETE FROM notifications
WHERE recipient_id = $1 AND type = $2 AND reference_id = $3
`

type DeleteNotificationByReferenceParams struct {
	RecipientID pgtype.UUID `json:"recipient_id"`
	Type        string      `json:"type"`
	ReferenceID pgtype.UUID `json:"reference_id"`
}

func (q *Queries) DeleteNotificationByReference(ctx context.Context, arg DeleteNotificationByReferenceParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationByReference, arg.RecipientID, arg.Type, arg.ReferenceID)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, recipient_id, actor_id, type, reference_id, reference_type, is_read, created_at, read_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getNotificationByReference = `-- name: GetNotificationByReference :one
SELECT id, recipient_id, actor_id, type, reference_id, reference_type, is_read, created_at, read_at
FROM notifications
WHERE recipient_id = $1 AND type = $2 AND reference_id = $3
LIMIT 1
`

type GetNotificationByReferenceParams struct {
	RecipientID pgtype.UUID `json:"recipient_id"`
	Type        string      `json:"type"`
	ReferenceID pgtype.UUID `json:"reference_id"`
}

func (q *Queries) GetNotificationByReference(ctx context.Context, arg GetNotificationByReferenceParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByReference, arg.RecipientID, arg.Type, arg.ReferenceID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) as count
FROM notifications
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, recipientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotificationsByRecipient = `-- name: ListNotificationsByRecipient :many
SELECT
    n.id,
    n.recipient_id,
    n.actor_id,
    u.username AS actor_username,
    u.display_name AS actor_display_name,
    u.avatar_url AS actor_avatar_url,
    n.type,
    n.reference_id,
    n.reference_type,
    n.is_read,
    n.created_at,
    n.read_at
FROM notifications n
JOIN users u ON u.id = n.actor_id
WHERE n.recipient_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByRecipientParams struct {
	RecipientID pgtype.UUID `json:"recipient_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListNotificationsByRecipientRow struct {
	ID               pgtype.UUID        `json:"id"`
	RecipientID      pgtype.UUID        `json:"recipient_id"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	ActorUsername    string             `json:"actor_username"`
	ActorDisplayName string             `json:"actor_display_name"`
	ActorAvatarUrl   pgtype.Text        `json:"actor_avatar_url"`
	Type             string             `json:"type"`
	ReferenceID      pgtype.UUID        `json:"reference_id"`
	ReferenceType    string             `json:"reference_type"`
	IsRead           bool               `json:"is_read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) ListNotificationsByRecipient(ctx context.Context, arg ListNotificationsByRecipientParams) ([]ListNotificationsByRecipientRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByRecipient, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsByRecipientRow
	for rows.Next() {
		var i ListNotificationsByRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.ActorUsername,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Type,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = TRUE, read_at = NOW()
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = TRUE, read_at = NOW()
WHERE id = $1 AND recipient_id = $2
RETURNING id, recipient_id, actor_id, type, reference_id, reference_type, is_read, created_at, read_at
`

type MarkNotificationReadParams struct {
	ID          pgtype.UUID `json:"id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
