// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, display_name, password_hash, status)
VALUES ($1, $2, $3, $4, $5, 'ONLINE')
RETURNING id, email, username, password_hash, display_name, bio, avatar_url, avatar_cloudinary_id, status, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	DisplayName  string      `json:"display_name"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.AvatarCloudinaryID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, username, password_hash, display_name, bio, avatar_url, avatar_cloudinary_id, status, last_seen_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.AvatarCloudinaryID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, username, password_hash, display_name, bio, avatar_url, avatar_cloudinary_id, status, last_seen_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.AvatarCloudinaryID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, email, username, password_hash, display_name, bio, avatar_url, avatar_cloudinary_id, status, last_seen_at, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.AvatarCloudinaryID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $1, last_seen_at = NOW() WHERE id = $2
`

type UpdateUserStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}
